### PR TITLE
hex color update

### PR DESCRIPTION
**Pull request by joshkordek3**
I added a way to show a color from hex, it would be very useful.

### CODE REVIEW

**Comment by joshkordek3** [comment]
sorry, created this by accident

**Comment by joshkordek3** [comment]
this just makes it possible to do it without using javascript

**Comment by kiate** [comment]
Thanks for the PR!
However, I think there's a more elegant way to achieve the same result. Do you mind adapting your code to maintain the consistency of EDUBIT RGB blocks? We already have 3 ways to select the colors. Just need to create a new color block which takes in the HEX code. What do you think?
rgbbit-colorblocks

**Comment by joshkordek3** [comment]
ok, I will try :)

**Comment by joshkordek3** [comment]
fixed :)

**Comment by kiate** [comment]
Great! It's working fine with the existing blocks.
I see that you've had verification for 3 char or 6 char in place. Maybe we can further verify user inputs by filtering out any char beyond 'F'? Any char beyond the hexadecimal range will be set to either '0' (min) or 'F' (max).

**Comment by joshkordek3** [comment]
hmmm, do you mean making people not able to type 1Z5DT4 or do you mean constraining it so that it just makes it max or minimum depending on the value? I know how to do the max or minimum...

**Comment by kiate** [comment]
MakeCode text input will take in any char. So I think we can only filter to min/max in this case.

**Comment by joshkordek3** [comment]
then its done, I made it constrain the number between 0 and 255

**Comment by kiate** [comment]
Sorry for the late response.
Can you have a look at this simplified code based on your ideas https://github.com/kiate/pxt-edubit/blob/faabae082085497486c0aeb438ca6ac7db44ae9d/rgb_bit.ts#L292

Changes:
- simplified the code for a smaller code size
- thus, only accept 6-char color hex code
- utilized `parseInt(string, radix)` for hex to int conversion
- utilized `edubit.limit( )` to constrain the data range

What do you think?

**Comment by joshkordek3** [comment]
Ah, now I'm sorry for the late response. Haha. Yeah, I think that's better.

**Comment by kiate** [comment]
Merged. Thanks @joshkordek3 !

**Pull request merged**
